// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tojtpdgftdiejlnqctgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvanRwZGdmdGRpZWpsbnFjdGdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NjM3NjQsImV4cCI6MjA1NzUzOTc2NH0.fRtcmyk2eFeAZbhJmzURWXo3JeVcFlwD46lwf-qioXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);